services:
  backend:
    build: .
    networks:
      - projeto_pi
    environment:
      PORT: 8080
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: toor
      ME_CONFIG_MONGODB_URL: mongodb://root:toor@mongo:27017/
    links:
      - 'db:mongo'
    ports:
      - 3333:3333
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    networks:
      - projeto_pi
    ports:
      - 27017:27017
networks:
  projeto_pi:
    external: false
  rua:
    external: true
